{"name": "Логин с неправильными учетными данными", "status": "passed", "description": "Тест проверяет попытку логина с неправильными учетными данными. Ожидается ошибка 401.", "steps": [{"name": "Попытка логина с email=nhflkfvear@example.com и password=dssiozcinrab", "status": "passed", "start": 1723209223254, "stop": 1723209223630}], "parameters": [{"name": "email", "value": "'nhflkfvear@example.com'"}, {"name": "password", "value": "'dssiozcinrab'"}], "start": 1723209223254, "stop": 1723209223631, "uuid": "e2873f82-a4ab-42b6-8cdf-11a2e4e8d972", "historyId": "f7069b617b0faa960707d3e99872e18b", "testCaseId": "ad4bdf1dbd143f644ff8c13f63194130", "fullName": "tests.test_user_login.TestUserLogin#test_login_incorrect_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "AmosovLenovo"}, {"name": "thread", "value": "11348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}